// Preset role options for the candidate headline. Tailored to early-stage
// startups so anyone joining a small team can pick a label that maps to
// what founders actually search for.
export const HEADLINE_OPTIONS: string[] = [
 "Technical Cofounder",
 "Non-Technical Cofounder",
 "Full-Stack Engineer",
 "Frontend Engineer",
 "Backend Engineer",
 "Mobile Engineer (iOS / Android)",
 "AI / ML Engineer",
 "Data Engineer",
 "DevOps / Infrastructure",
 "Product Designer",
 "Brand / Visual Designer",
 "Product Manager",
 "Growth Marketer",
 "Sales Lead",
 "Operations Lead",
 "Business Development",
 "Community Partner",
 "Content Creator",
 "Founder Looking for Cofounder",
 "Generalist (Wears Many Hats)",
];

// Country-only location list. Alphabetical so the Autocomplete narrows
// naturally as the user types. UN-recognized states plus common
// territories (Hong Kong, Macao, Palestine, Puerto Rico, Taiwan,
// Vatican City, Kosovo). No cities, no remote/anywhere - strictly
// countries. Free-text entries are still allowed (allowCustom on the
// picker) so anything outside this list can be typed manually.
export const LOCATION_OPTIONS: string[] = [
 "Afghanistan",
 "Albania",
 "Algeria",
 "Andorra",
 "Angola",
 "Antigua and Barbuda",
 "Argentina",
 "Armenia",
 "Australia",
 "Austria",
 "Azerbaijan",
 "Bahamas",
 "Bahrain",
 "Bangladesh",
 "Barbados",
 "Belarus",
 "Belgium",
 "Belize",
 "Benin",
 "Bhutan",
 "Bolivia",
 "Bosnia and Herzegovina",
 "Botswana",
 "Brazil",
 "Brunei",
 "Bulgaria",
 "Burkina Faso",
 "Burundi",
 "Cabo Verde",
 "Cambodia",
 "Cameroon",
 "Canada",
 "Central African Republic",
 "Chad",
 "Chile",
 "China",
 "Colombia",
 "Comoros",
 "Congo (Brazzaville)",
 "Congo (Kinshasa)",
 "Costa Rica",
 "Croatia",
 "Cuba",
 "Cyprus",
 "Czech Republic",
 "Denmark",
 "Djibouti",
 "Dominica",
 "Dominican Republic",
 "Ecuador",
 "Egypt",
 "El Salvador",
 "Equatorial Guinea",
 "Eritrea",
 "Estonia",
 "Eswatini",
 "Ethiopia",
 "Fiji",
 "Finland",
 "France",
 "Gabon",
 "Gambia",
 "Georgia",
 "Germany",
 "Ghana",
 "Greece",
 "Grenada",
 "Guatemala",
 "Guinea",
 "Guinea-Bissau",
 "Guyana",
 "Haiti",
 "Honduras",
 "Hong Kong",
 "Hungary",
 "Iceland",
 "India",
 "Indonesia",
 "Iran",
 "Iraq",
 "Ireland",
 "Israel",
 "Italy",
 "Ivory Coast",
 "Jamaica",
 "Japan",
 "Jordan",
 "Kazakhstan",
 "Kenya",
 "Kiribati",
 "Kosovo",
 "Kuwait",
 "Kyrgyzstan",
 "Laos",
 "Latvia",
 "Lebanon",
 "Lesotho",
 "Liberia",
 "Libya",
 "Liechtenstein",
 "Lithuania",
 "Luxembourg",
 "Macao",
 "Madagascar",
 "Malawi",
 "Malaysia",
 "Maldives",
 "Mali",
 "Malta",
 "Marshall Islands",
 "Mauritania",
 "Mauritius",
 "Mexico",
 "Micronesia",
 "Moldova",
 "Monaco",
 "Mongolia",
 "Montenegro",
 "Morocco",
 "Mozambique",
 "Myanmar",
 "Namibia",
 "Nauru",
 "Nepal",
 "Netherlands",
 "New Zealand",
 "Nicaragua",
 "Niger",
 "Nigeria",
 "North Korea",
 "North Macedonia",
 "Norway",
 "Oman",
 "Pakistan",
 "Palau",
 "Palestine",
 "Panama",
 "Papua New Guinea",
 "Paraguay",
 "Peru",
 "Philippines",
 "Poland",
 "Portugal",
 "Puerto Rico",
 "Qatar",
 "Romania",
 "Russia",
 "Rwanda",
 "Saint Kitts and Nevis",
 "Saint Lucia",
 "Saint Vincent and the Grenadines",
 "Samoa",
 "San Marino",
 "Sao Tome and Principe",
 "Saudi Arabia",
 "Senegal",
 "Serbia",
 "Seychelles",
 "Sierra Leone",
 "Singapore",
 "Slovakia",
 "Slovenia",
 "Solomon Islands",
 "Somalia",
 "South Africa",
 "South Korea",
 "South Sudan",
 "Spain",
 "Sri Lanka",
 "Sudan",
 "Suriname",
 "Sweden",
 "Switzerland",
 "Syria",
 "Taiwan",
 "Tajikistan",
 "Tanzania",
 "Thailand",
 "Timor-Leste",
 "Togo",
 "Tonga",
 "Trinidad and Tobago",
 "Tunisia",
 "Turkey",
 "Turkmenistan",
 "Tuvalu",
 "Uganda",
 "Ukraine",
 "United Arab Emirates",
 "United Kingdom",
 "United States",
 "Uruguay",
 "Uzbekistan",
 "Vanuatu",
 "Vatican City",
 "Venezuela",
 "Vietnam",
 "Yemen",
 "Zambia",
 "Zimbabwe",
];

// Broad business / startup skill categories. Drives the Skills
// dropdown in the Profile setup wizard, the Profile edit view, the
// project criteria, and the Match filters. Kept intentionally broad
// (a couple dozen top-level functions, not 200 framework names) so
// the picker reads as a quick "which side of the org do you cover?"
// vs a long checklist. Free-text fallback is still on (allowCustom
// on TagInput) so anything niche can be typed manually.
export const SKILLS_OPTIONS: string[] = [
 "Full-stack engineering",
 "Frontend engineering",
 "Backend / infrastructure engineering",
 "AI/ML engineering",
 "Product design",
 "Customer research",
 "Sales",
 "Distribution / growth marketing",
 "Content and storytelling",
 "Fundraising",
];

// C-level role a partner wants to play in their next venture.
// Only meaningful on the partner-side of Profile; founders ignore
// this field. Renders as a pill on the partner's Match card.
export const PARTNER_ROLE_OPTIONS: ReadonlyArray<{
 value: "CTO" | "CPO" | "CMO" | "CRO" | "CDO" | "COO" | "CFO";
 label: string;
 description: string;
}> = [
 { value: "CTO", label: "CTO", description: "Engineering" },
 { value: "CPO", label: "CPO", description: "Product" },
 { value: "CMO", label: "CMO", description: "Marketing" },
 { value: "CRO", label: "CRO", description: "Sales / revenue" },
 { value: "CDO", label: "CDO", description: "Design" },
 { value: "COO", label: "COO", description: "Operations" },
 { value: "CFO", label: "CFO", description: "Finance" },
];

// Kept (but not exported) so referencing tools that scrape this file
// for example skills still find values. The dropdown uses
// SKILLS_OPTIONS above; this is a no-runtime-cost reference array.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _SKILLS_OPTIONS_GRANULAR_LEGACY: readonly string[] = [
 // Languages
 "JavaScript",
 "TypeScript",
 "Python",
 "Go",
 "Rust",
 "Java",
 "Kotlin",
 "Swift",
 "Ruby",
 "PHP",
 "C",
 "C++",
 "C#",
 "Scala",
 "Elixir",
 "Erlang",
 "Haskell",
 "Lua",
 "R",
 "Dart",
 "Solidity",
 "SQL",
 "Bash",
 "PowerShell",
 // Frontend
 "React",
 "Next.js",
 "Vue",
 "Nuxt",
 "Angular",
 "Svelte",
 "SvelteKit",
 "Solid.js",
 "Astro",
 "Remix",
 "Tailwind CSS",
 "CSS",
 "HTML",
 "SCSS / Sass",
 "Webpack",
 "Vite",
 "Storybook",
 "Three.js",
 "WebGL",
 "WebGPU",
 "WebRTC",
 "Web Components",
 "Accessibility (a11y)",
 // Mobile
 "iOS (Swift)",
 "Android (Kotlin)",
 "React Native",
 "Flutter",
 "Expo",
 "SwiftUI",
 "Jetpack Compose",
 // Backend
 "Node.js",
 "Express",
 "Fastify",
 "NestJS",
 "Django",
 "Flask",
 "FastAPI",
 "Rails",
 "Laravel",
 "Spring",
 "ASP.NET",
 "Phoenix (Elixir)",
 "Actix",
 "tRPC",
 "GraphQL",
 "REST APIs",
 "gRPC",
 "WebSockets",
 "Microservices",
 "Distributed Systems",
 "Event-driven architecture",
 "Serverless",
 // Databases
 "PostgreSQL",
 "MySQL",
 "SQLite",
 "MongoDB",
 "Redis",
 "DynamoDB",
 "Cassandra",
 "BigQuery",
 "Snowflake",
 "ClickHouse",
 "Elasticsearch",
 "Supabase",
 "Firebase",
 "Prisma",
 "Drizzle",
 "Knex",
 "SQLAlchemy",
 // Cloud / DevOps
 "AWS",
 "GCP",
 "Azure",
 "Vercel",
 "Cloudflare",
 "Fly.io",
 "Render",
 "Heroku",
 "DigitalOcean",
 "Docker",
 "Kubernetes",
 "Terraform",
 "Pulumi",
 "Ansible",
 "GitHub Actions",
 "CircleCI",
 "GitLab CI",
 "Linux",
 "Networking",
 "Observability",
 "Datadog",
 "Prometheus",
 "Grafana",
 "Sentry",
 // AI / ML
 "Machine Learning",
 "Deep Learning",
 "Computer Vision",
 "NLP",
 "LLMs",
 "Prompt Engineering",
 "RAG",
 "Embeddings",
 "Fine-tuning",
 "TensorFlow",
 "PyTorch",
 "scikit-learn",
 "Hugging Face",
 "LangChain",
 "LlamaIndex",
 "OpenAI API",
 "Anthropic API",
 "Vector Databases",
 "Recommender Systems",
 "Reinforcement Learning",
 "MLOps",
 // Data
 "Data Engineering",
 "ETL / ELT",
 "Airflow",
 "dbt",
 "Spark",
 "Kafka",
 "Pandas",
 "NumPy",
 "Looker",
 "Tableau",
 "Power BI",
 "Analytics",
 "A/B Testing",
 "Experimentation",
 // Web3 / Crypto
 "Ethereum",
 "Solana",
 "Smart Contracts",
 "DeFi",
 "NFTs",
 "Cryptography",
 "Zero-knowledge proofs",
 // Hardware / Robotics
 "Embedded systems",
 "Firmware",
 "Robotics",
 "Computer Vision (Robotics)",
 "ROS",
 "Electrical Engineering",
 "Mechanical Engineering",
 "PCB Design",
 // Design
 "UI Design",
 "UX Research",
 "Product Design",
 "Visual Design",
 "Brand Design",
 "Motion Design",
 "Illustration",
 "Figma",
 "Sketch",
 "Adobe XD",
 "Webflow",
 "Framer",
 "Design Systems",
 "Prototyping",
 // Product
 "Product Management",
 "Product Strategy",
 "Roadmapping",
 "User Research",
 "Customer Discovery",
 "Pricing",
 "Onboarding",
 // Growth / Marketing
 "Growth Marketing",
 "SEO",
 "Content Marketing",
 "Performance Marketing",
 "Paid Acquisition",
 "Lifecycle Marketing",
 "Email Marketing",
 "Social Media",
 "Community Building",
 "Brand Marketing",
 "PR",
 "Influencer Marketing",
 "Affiliate Marketing",
 "Partnerships",
 // Sales / BD
 "Sales",
 "B2B Sales",
 "Enterprise Sales",
 "SaaS Sales",
 "Sales Engineering",
 "Business Development",
 "Channel Partnerships",
 "Account Management",
 "Customer Success",
 "Solutions Engineering",
 // Business / Operations
 "Fundraising",
 "Venture Capital",
 "Pitch Decks",
 "Financial Modeling",
 "Accounting",
 "Bookkeeping",
 "Legal",
 "Contracts",
 "Hiring / Recruiting",
 "Operations",
 "Supply Chain",
 "Logistics",
 "Customer Support",
 "Project Management",
 // Domain
 "Fintech",
 "Healthtech",
 "Edtech",
 "Climate Tech",
 "Cybersecurity",
 "Privacy",
 "Compliance",
 "Marketplaces",
 "B2B SaaS",
 "Consumer Apps",
 "Creator Tools",
 "Gaming",
 "Media",
];

// Common commitment options. Reused by both candidate and project sides.
export const COMMITMENT_OPTIONS: string[] = [
 "Full-time",
 "Part-time",
 "Contract",
 "Advisor",
 "Equity-only",
 "Open to discuss",
];
export const BUSINESS_TYPE_OPTIONS: string[] = [
 // Models
 "SaaS",
 "B2B SaaS",
 "B2C SaaS",
 "Marketplace",
 "Two-sided Marketplace",
 "Platform",
 "API / Developer Tools",
 "Open Source",
 "Hardware",
 "Hardware + Software",
 "Consumer App",
 "Mobile-first Consumer",
 "Subscription",
 "E-commerce",
 "DTC (Direct-to-Consumer)",
 "Marketplace (Services)",
 "Aggregator",
 "Network / Community",
 "Agency / Studio",
 "Media",
 "Content / Creator",
 // Verticals
 "Fintech",
 "Banking / Neobank",
 "Lending",
 "Insurance / Insurtech",
 "Wealth / Investment",
 "Crypto / Web3",
 "DeFi",
 "Payments",
 "Healthcare",
 "Digital Health",
 "Telehealth",
 "Biotech",
 "Pharma",
 "Mental Health",
 "Wellness",
 "Climate / Sustainability",
 "Energy",
 "ClimateTech",
 "CleanTech",
 "Carbon",
 "Education / Edtech",
 "K-12",
 "Higher Ed",
 "Workforce / Upskilling",
 "Real Estate / Proptech",
 "Construction / Contech",
 "Logistics",
 "Supply Chain",
 "Last-Mile Delivery",
 "Manufacturing / Industrial",
 "Robotics",
 "Defense / Government",
 "GovTech",
 "LegalTech",
 "RegTech",
 "Compliance",
 "HR / People Tech",
 "Recruiting",
 "Productivity",
 "Vertical SaaS",
 "Horizontal SaaS",
 "Dev Tools",
 "Infrastructure",
 "Data / Analytics",
 "AI / ML",
 "Generative AI",
 "AI Agents",
 "Computer Vision",
 "Audio / Voice",
 "Video",
 "Streaming",
 "Gaming",
 "Esports",
 "Music",
 "Social",
 "Dating",
 "Community",
 "Creator Tools",
 "Travel",
 "Hospitality",
 "Food / Restaurants",
 "Grocery",
 "Agriculture / Agtech",
 "Mobility / Transportation",
 "Automotive",
 "Aerospace",
 "Space",
 "Robotics",
 "IoT",
 "Security",
 "Privacy",
 "Marketing / Adtech",
 "Sales Tech",
 "Customer Support",
 "Operations",
 "Other",
];
