// Preset role options for the candidate headline. Tailored to early-stage
// startups so anyone joining a small team can pick a label that maps to
// what founders actually search for.
export const HEADLINE_OPTIONS: string[] = [
  "Technical Cofounder",
  "Non-Technical Cofounder",
  "Full-Stack Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Mobile Engineer (iOS / Android)",
  "AI / ML Engineer",
  "Data Engineer",
  "DevOps / Infrastructure",
  "Product Designer",
  "Brand / Visual Designer",
  "Product Manager",
  "Growth Marketer",
  "Sales Lead",
  "Operations Lead",
  "Business Development",
  "Community Partner",
  "Content Creator",
  "Founder Looking for Cofounder",
  "Generalist (Wears Many Hats)",
];

// Curated list of major startup hubs and "remote" options for location
// autocomplete. Keeps suggestions focused on places founders actually
// look. Free-text entries are still allowed so anyone outside this list
// can type their own city.
export const LOCATION_OPTIONS: string[] = [
  "Remote",
  "Anywhere",
  "Hybrid",
  // North America
  "San Francisco, CA",
  "South Bay, CA",
  "Palo Alto, CA",
  "Mountain View, CA",
  "Berkeley, CA",
  "Oakland, CA",
  "Los Angeles, CA",
  "San Diego, CA",
  "Sacramento, CA",
  "Seattle, WA",
  "Portland, OR",
  "Denver, CO",
  "Boulder, CO",
  "Salt Lake City, UT",
  "Phoenix, AZ",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "San Antonio, TX",
  "Chicago, IL",
  "Minneapolis, MN",
  "Detroit, MI",
  "Pittsburgh, PA",
  "Philadelphia, PA",
  "New York, NY",
  "Brooklyn, NY",
  "Boston, MA",
  "Cambridge, MA",
  "Washington, DC",
  "Atlanta, GA",
  "Miami, FL",
  "Tampa, FL",
  "Orlando, FL",
  "Raleigh, NC",
  "Charlotte, NC",
  "Nashville, TN",
  "New Orleans, LA",
  "Honolulu, HI",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Calgary, Canada",
  "Mexico City, Mexico",
  // Europe
  "London, UK",
  "Manchester, UK",
  "Edinburgh, UK",
  "Dublin, Ireland",
  "Paris, France",
  "Lyon, France",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Brussels, Belgium",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Milan, Italy",
  "Rome, Italy",
  "Vienna, Austria",
  "Warsaw, Poland",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Athens, Greece",
  "Istanbul, Turkey",
  // Middle East / Africa
  "Tel Aviv, Israel",
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Riyadh, Saudi Arabia",
  "Cairo, Egypt",
  "Lagos, Nigeria",
  "Nairobi, Kenya",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  // Asia
  "Singapore",
  "Hong Kong",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Shenzhen, China",
  "Bangalore, India",
  "Mumbai, India",
  "Delhi, India",
  "Hyderabad, India",
  "Chennai, India",
  "Pune, India",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Bangkok, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Kuala Lumpur, Malaysia",
  "Taipei, Taiwan",
  // Oceania
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  // South America
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "Bogotá, Colombia",
  "Lima, Peru",
];

// Common commitment options. Reused by both candidate and project sides.
export const COMMITMENT_OPTIONS: string[] = [
  "Full-time",
  "Part-time",
  "Contract",
  "Advisor",
  "Equity-only",
  "Open to discuss",
];
export const BUSINESS_TYPE_OPTIONS: string[] = [
  // Models
  "SaaS",
  "B2B SaaS",
  "B2C SaaS",
  "Marketplace",
  "Two-sided Marketplace",
  "Platform",
  "API / Developer Tools",
  "Open Source",
  "Hardware",
  "Hardware + Software",
  "Consumer App",
  "Mobile-first Consumer",
  "Subscription",
  "E-commerce",
  "DTC (Direct-to-Consumer)",
  "Marketplace (Services)",
  "Aggregator",
  "Network / Community",
  "Agency / Studio",
  "Media",
  "Content / Creator",
  // Verticals
  "Fintech",
  "Banking / Neobank",
  "Lending",
  "Insurance / Insurtech",
  "Wealth / Investment",
  "Crypto / Web3",
  "DeFi",
  "Payments",
  "Healthcare",
  "Digital Health",
  "Telehealth",
  "Biotech",
  "Pharma",
  "Mental Health",
  "Wellness",
  "Climate / Sustainability",
  "Energy",
  "ClimateTech",
  "CleanTech",
  "Carbon",
  "Education / Edtech",
  "K-12",
  "Higher Ed",
  "Workforce / Upskilling",
  "Real Estate / Proptech",
  "Construction / Contech",
  "Logistics",
  "Supply Chain",
  "Last-Mile Delivery",
  "Manufacturing / Industrial",
  "Robotics",
  "Defense / Government",
  "GovTech",
  "LegalTech",
  "RegTech",
  "Compliance",
  "HR / People Tech",
  "Recruiting",
  "Productivity",
  "Vertical SaaS",
  "Horizontal SaaS",
  "Dev Tools",
  "Infrastructure",
  "Data / Analytics",
  "AI / ML",
  "Generative AI",
  "AI Agents",
  "Computer Vision",
  "Audio / Voice",
  "Video",
  "Streaming",
  "Gaming",
  "Esports",
  "Music",
  "Social",
  "Dating",
  "Community",
  "Creator Tools",
  "Travel",
  "Hospitality",
  "Food / Restaurants",
  "Grocery",
  "Agriculture / Agtech",
  "Mobility / Transportation",
  "Automotive",
  "Aerospace",
  "Space",
  "Robotics",
  "IoT",
  "Security",
  "Privacy",
  "Marketing / Adtech",
  "Sales Tech",
  "Customer Support",
  "Operations",
  "Other",
];
