-- ⚠ DESTRUCTIVE - reads the comments before you do anything.
--
-- This script deletes EVERY auth.users row except one named owner
-- account. That includes real users who signed up if any exist.
-- It does not distinguish fake from real - so DO NOT use it unless
-- you've verified you're the only real account on the platform.
--
-- The safer path:
--   1. Run supabase/scripts/list_all_accounts.sql first to see what's
--      in the DB.
--   2. Send the names of the fake accounts back so I can add them
--      to supabase/migrations/0031_remove_fake_accounts.sql, which
--      only deletes by name allowlist.
--
-- If you've verified you are the only real account and want to use
-- the nuclear option, uncomment the final block and substitute your
-- email.
--
-- Everything FK'd to auth.users is ON DELETE CASCADE, so deleting
-- the auth row wipes profiles, projects, saved_*, chat_*,
-- notifications, push_tokens, user_reports for every purged user.
--
-- THIS IS NOT A MIGRATION. It lives under supabase/scripts/ so it
-- doesn't get auto-applied. Run by hand only.

-- COMMENTED OUT BY DEFAULT. Uncomment + substitute your email to
-- arm. Until uncommented, running this script is a no-op.
--
-- delete from auth.users
-- where lower(email) <> lower('YOUR_REAL_EMAIL@example.com');
