// Mirror of src/lib/options.ts on web. Same role / commitment / location
// presets so mobile and web profiles share the same vocabulary.

export const HEADLINE_OPTIONS: string[] = [
  "Technical Cofounder",
  "Non-Technical Cofounder",
  "Full-Stack Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Mobile Engineer (iOS / Android)",
  "AI / ML Engineer",
  "Data Engineer",
  "DevOps / Infrastructure",
  "Product Designer",
  "Brand / Visual Designer",
  "Product Manager",
  "Growth Marketer",
  "Sales Lead",
  "Operations Lead",
  "Business Development",
  "Community Builder",
  "Content Creator",
  "Founder Looking for Cofounder",
  "Generalist (Wears Many Hats)",
];

export const COMMITMENT_OPTIONS: string[] = [
  "Full-time",
  "Part-time",
  "Contract",
  "Advisor",
  "Equity-only",
  "Open to discuss",
];

// Top startup hubs + remote/hybrid options. Free text still allowed in
// the input itself, but suggesting from this list keeps results clean.
export const LOCATION_OPTIONS: string[] = [
  "Remote",
  "Anywhere",
  "Hybrid",
  "San Francisco, CA",
  "Palo Alto, CA",
  "Mountain View, CA",
  "Berkeley, CA",
  "Oakland, CA",
  "Los Angeles, CA",
  "San Diego, CA",
  "Seattle, WA",
  "Portland, OR",
  "Denver, CO",
  "Boulder, CO",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "Chicago, IL",
  "New York, NY",
  "Brooklyn, NY",
  "Boston, MA",
  "Cambridge, MA",
  "Washington, DC",
  "Atlanta, GA",
  "Miami, FL",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Mexico City, Mexico",
  "London, UK",
  "Berlin, Germany",
  "Amsterdam, Netherlands",
  "Paris, France",
  "Stockholm, Sweden",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Lisbon, Portugal",
  "Tel Aviv, Israel",
  "Dubai, UAE",
  "Singapore",
  "Tokyo, Japan",
  "Bangalore, India",
  "Mumbai, India",
  "Sydney, Australia",
  "Melbourne, Australia",
  "São Paulo, Brazil",
];
