// Mirror of src/lib/options.ts on web. Same role / commitment / location
// presets so mobile and web profiles share the same vocabulary.

export const HEADLINE_OPTIONS: string[] = [
  "Technical Cofounder",
  "Non-Technical Cofounder",
  "Full-Stack Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Mobile Engineer (iOS / Android)",
  "AI / ML Engineer",
  "Data Engineer",
  "DevOps / Infrastructure",
  "Product Designer",
  "Brand / Visual Designer",
  "Product Manager",
  "Growth Marketer",
  "Sales Lead",
  "Operations Lead",
  "Business Development",
  "Community Builder",
  "Content Creator",
  "Founder Looking for Cofounder",
  "Generalist (Wears Many Hats)",
];

export const COMMITMENT_OPTIONS: string[] = [
  "Full-time",
  "Part-time",
  "Contract",
  "Advisor",
  "Equity-only",
  "Open to discuss",
];

// All ISO 3166 countries plus three remote/hybrid presets at the top.
// Ordering: remote presets first, then alphabetical countries.
export const LOCATION_OPTIONS: string[] = [
  "Remote",
  "Anywhere",
  "Hybrid",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// Comprehensive skills catalog. Used for both founder criteria
// (skills they need on a project) and builder profiles (skills they
// have). Grouped loosely by area so the search-as-you-type experience
// surfaces related items.
export const SKILLS_OPTIONS: string[] = [
  // Engineering / general
  "Software Engineering",
  "Full-Stack Engineering",
  "Frontend Engineering",
  "Backend Engineering",
  "Mobile Engineering",
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
  "Web3 / Blockchain",
  "Smart Contracts",
  "Solidity",
  "Embedded Systems",
  "Robotics",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "AR / VR",
  "Computer Vision",
  "Quantum Computing",
  // Frontend
  "React",
  "Next.js",
  "Vue",
  "Svelte",
  "Angular",
  "TypeScript",
  "JavaScript",
  "HTML / CSS",
  "Tailwind CSS",
  "Design Systems",
  "Animation",
  "Webflow",
  "Framer",
  "WebGL",
  "Three.js",
  // Backend
  "Node.js",
  "Python",
  "Go",
  "Rust",
  "Ruby on Rails",
  "Java",
  "Kotlin",
  "Swift",
  "C#",
  "C++",
  "Elixir",
  "PHP",
  "Laravel",
  "Django",
  "FastAPI",
  "GraphQL",
  "REST APIs",
  "gRPC",
  "Microservices",
  "Distributed Systems",
  "Real-time Systems",
  "Event-Driven Architecture",
  "Performance Optimization",
  "Concurrency",
  "Compilers",
  "Operating Systems",
  // Data
  "Postgres",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "BigQuery",
  "Snowflake",
  "Data Engineering",
  "ETL / ELT",
  "Airflow",
  "dbt",
  "Spark",
  "Kafka",
  "Data Warehousing",
  "Streaming",
  "OLAP",
  // AI / ML
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "LLMs",
  "RAG",
  "Vector Databases",
  "Embeddings",
  "Fine-tuning",
  "Prompt Engineering",
  "Reinforcement Learning",
  "TensorFlow",
  "PyTorch",
  "Hugging Face",
  "OpenAI APIs",
  "Anthropic APIs",
  "MLOps",
  "AI Agents",
  "Computer Vision (ML)",
  // Infra / DevOps / Security
  "DevOps",
  "Site Reliability Engineering",
  "AWS",
  "GCP",
  "Azure",
  "Cloudflare",
  "Vercel",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Linux Administration",
  "Networking",
  "Observability",
  "Monitoring",
  "Logging",
  "CI / CD",
  "Security",
  "Application Security",
  "Cryptography",
  "Penetration Testing",
  "Compliance (SOC 2, HIPAA, GDPR)",
  "Cost Optimization",
  // Mobile / hardware specifics
  "App Store Optimization",
  "Push Notifications",
  "Offline-first",
  "Realtime Sync",
  "Hardware Prototyping",
  "Firmware",
  "PCB Design",
  // Product / Design
  "Product Management",
  "Product Strategy",
  "Roadmapping",
  "User Research",
  "UX Research",
  "Usability Testing",
  "UX Design",
  "UI Design",
  "Interaction Design",
  "Visual Design",
  "Brand Design",
  "Logo Design",
  "Typography",
  "Illustration",
  "Iconography",
  "Motion Design",
  "Figma",
  "Sketch",
  "Adobe Creative Suite",
  "Industrial Design",
  "Service Design",
  "Information Architecture",
  // Growth / Marketing / Sales
  "Growth",
  "Performance Marketing",
  "Paid Acquisition",
  "SEO",
  "Content Marketing",
  "Copywriting",
  "Brand Marketing",
  "Social Media",
  "Community",
  "Influencer Marketing",
  "Email Marketing",
  "Lifecycle Marketing",
  "PR / Communications",
  "Events",
  "Partnerships",
  "Sales",
  "B2B Sales",
  "Enterprise Sales",
  "Outbound Sales",
  "Inside Sales",
  "Sales Engineering",
  "Solution Architecture",
  "Customer Success",
  "Account Management",
  "Demand Generation",
  "Sales Operations",
  "Revenue Operations",
  // Business / Ops
  "Business Development",
  "Strategy",
  "Operations",
  "Supply Chain",
  "Logistics",
  "Procurement",
  "Manufacturing",
  "Project Management",
  "Program Management",
  "Customer Support",
  "Hiring / Recruiting",
  "People Ops",
  "HR",
  "Talent Management",
  "Org Design",
  "Culture",
  "Diversity, Equity, Inclusion",
  // Finance / Legal
  "Finance",
  "Financial Modeling",
  "FP&A",
  "Accounting",
  "Bookkeeping",
  "Tax",
  "Treasury",
  "Investor Relations",
  "Fundraising",
  "Pitching",
  "M&A",
  "Corporate Development",
  "Legal",
  "Contracts",
  "IP / Patents",
  "Privacy Law",
  "Regulatory Compliance",
  // Vertical / domain
  "Fintech",
  "Payments",
  "Banking",
  "Insurance",
  "Healthcare",
  "Biotech",
  "Pharma",
  "Climate / Sustainability",
  "Energy",
  "Real Estate / Proptech",
  "Education / Edtech",
  "Logistics / Supply Chain",
  "E-commerce",
  "Retail",
  "Consumer Apps",
  "Gaming",
  "Media / Entertainment",
  "Music",
  "Creator Tools",
  "Social",
  "Dating",
  "Travel",
  "Hospitality",
  "Food / Restaurants",
  "Agriculture / Agtech",
  "Manufacturing / Industrial",
  "Construction / Contech",
  "Defense",
  "Aerospace",
  "Automotive / Mobility",
  "Logistics",
  "Government / Civic Tech",
  "Nonprofit",
];

// Business / project type taxonomy. Founders pick one when posting a
// project; builders can filter Browse by it. Mixes business model
// (SaaS, Marketplace, etc.) with industry verticals so the founder
// can describe the venture however reads most naturally to them.
export const BUSINESS_TYPE_OPTIONS: string[] = [
  // Models
  "SaaS",
  "B2B SaaS",
  "B2C SaaS",
  "Marketplace",
  "Two-sided Marketplace",
  "Platform",
  "API / Developer Tools",
  "Open Source",
  "Hardware",
  "Hardware + Software",
  "Consumer App",
  "Mobile-first Consumer",
  "Subscription",
  "E-commerce",
  "DTC (Direct-to-Consumer)",
  "Marketplace (Services)",
  "Aggregator",
  "Network / Community",
  "Agency / Studio",
  "Media",
  "Content / Creator",
  // Verticals
  "Fintech",
  "Banking / Neobank",
  "Lending",
  "Insurance / Insurtech",
  "Wealth / Investment",
  "Crypto / Web3",
  "DeFi",
  "Payments",
  "Healthcare",
  "Digital Health",
  "Telehealth",
  "Biotech",
  "Pharma",
  "Mental Health",
  "Wellness",
  "Climate / Sustainability",
  "Energy",
  "ClimateTech",
  "CleanTech",
  "Carbon",
  "Education / Edtech",
  "K-12",
  "Higher Ed",
  "Workforce / Upskilling",
  "Real Estate / Proptech",
  "Construction / Contech",
  "Logistics",
  "Supply Chain",
  "Last-Mile Delivery",
  "Manufacturing / Industrial",
  "Robotics",
  "Defense / Government",
  "GovTech",
  "LegalTech",
  "RegTech",
  "Compliance",
  "HR / People Tech",
  "Recruiting",
  "Productivity",
  "Vertical SaaS",
  "Horizontal SaaS",
  "Dev Tools",
  "Infrastructure",
  "Data / Analytics",
  "AI / ML",
  "Generative AI",
  "AI Agents",
  "Computer Vision",
  "Audio / Voice",
  "Video",
  "Streaming",
  "Gaming",
  "Esports",
  "Music",
  "Social",
  "Dating",
  "Community",
  "Creator Tools",
  "Travel",
  "Hospitality",
  "Food / Restaurants",
  "Grocery",
  "Agriculture / Agtech",
  "Mobility / Transportation",
  "Automotive",
  "Aerospace",
  "Space",
  "Robotics",
  "IoT",
  "Security",
  "Privacy",
  "Marketing / Adtech",
  "Sales Tech",
  "Customer Support",
  "Operations",
  "Other",
];
